# Generated by Django 3.2 on 2022-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='closed',
            field=models.DateTimeField(blank=True),
        ),
    ]
