# Generated by Django 3.2 on 2022-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0002_alter_animal_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='closed',
            field=models.DateTimeField(null=True),
        ),
    ]
