# Generated by Django 3.2 on 2022-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0003_alter_animal_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Żeńska'), (2, 'Męska'), (3, 'Nieznana')]),
        ),
    ]
