# Generated by Django 3.2 on 2022-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0005_rename_closed_animal_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='closed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
