# Generated by Django 3.2 on 2022-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0006_auto_20220714_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
