# Generated by Django 3.2 on 2022-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0008_alter_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
