# Generated by Django 3.2 on 2022-07-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Better_life', '0009_alter_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
